export  const sliderData = [
  {
    image: "./img/sicilia/sic_2017-4.jpg",
    alt: "Work in Progress",
    text: "Work in progress",
    id: 0,
  },
  {
    image: "./img/sicilia/sic_2017-6.jpg",
    alt: "Work in Progress",
    text: "We are working on it",
    id: 1,
  },
  {
    image: "./img/sicilia/sic_2017-24.jpg",
    alt: "Work in Progress",
    text: "Almost there, stay tuned",
    id: 2,
  },
  {
    image: "./img/sicilia/sic_2017-27.jpg",
    alt: "Work in Progress",
    text: "Coming Soon",
    id: 3,
  },
  {
    image: "./img/sicilia/sic_2017-30.jpg",
    alt: "Work in Progress",
    text: "Work in progress",
    id: 0,
  },
  {
    image: "./img/sicilia/sic_2017-37a.jpg",
    alt: "Work in Progress",
    text: "We are working on it",
    id: 1,
  },
  {
    image: "./img/sicilia/sic_2017-54.jpg",
    alt: "Work in Progress",
    text: "Almost there, stay tuned",
    id: 2,
  },
  {
    image: "./img/sicilia/sic_2017-58.jpg",
    alt: "Work in Progress",
    text: "Work in progress",
    id: 0,
  },
  {
    image: "./img/sicilia/sic_2017-66.jpg",
    alt: "Work in Progress",
    text: "We are working on it",
    id: 1,
  },
  {
    image: "./img/sicilia/sic_2017-80.jpg",
    alt: "Work in Progress",
    text: "Almost there, stay tuned",
    id: 2,
  },
  {
    image: "./img/sicilia/sic_2017-81.jpg",
    alt: "Work in Progress",
    text: "Work in progress",
    id: 0,
  },
  {
    image: "./img/sicilia/sic_2017-82.jpg",
    alt: "Work in Progress",
    text: "We are working on it",
    id: 1,
  },
  {
    image: "./img/sicilia/sic_2017-86.jpg",
    alt: "Work in Progress",
    text: "Almost there, stay tuned",
    id: 2,
  },
  {
    image: "./img/sicilia/sic_2017-92.jpg",
    alt: "Work in Progress",
    text: "Work in progress",
    id: 0,
  },
  {
    image: "./img/sicilia/sic_2017-98.jpg",
    alt: "Work in Progress",
    text: "We are working on it",
    id: 1,
  },
  {
    image: "./img/sicilia/sic_2017-102.jpg",
    alt: "Work in Progress",
    text: "Almost there, stay tuned",
    id: 2,
  },
  {
    image: "./img/sicilia/sic_2017-107.jpg",
    alt: "Work in Progress",
    text: "Work in progress",
    id: 0,
  },
  {
    image: "./img/sicilia/sic_2017-111.jpg",
    alt: "Work in Progress",
    text: "We are working on it",
    id: 1,
  },
  {
    image: "./img/sicilia/sicilia2017_184.jpg",
    alt: "Work in Progress",
    text: "Almost there, stay tuned",
    id: 2,
  },
]